<x-guest-layout>
    <section class="bg-white dark:bg-gray-900">
            <div class="flex justify-between max-w-screen-xl px-4 py-8 mx-auto lg:gap-12 xl:gap-12 lg:py-12">
                <div class="w-full ">
                    <h1 class=" mb-4 text-4xl font-extrabold text-justify tracking-tight leading-none md:text-5xl xl:text-6xl dark:text-white">
                       Some static content.
                    </h1>
                    <p class="mb-4 font-light text-justify text-gray-500 lg:mb-4 md:text-lg lg:text-xl dark:text-gray-400">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab accusamus architecto dolorem earum expedita fuga incidunt magni, modi, nam nisi nobis odit quam quas quibusdam quis recusandae tempore velit vero vitae, voluptatum! A ab accusamus accusantium autem debitis, dicta illum inventore libero, magnam minima nihil odit officiis omnis quasi quidem repudiandae sequi, similique tempora temporibus voluptatum? Animi consectetur, incidunt? Autem enim, voluptate. Alias distinctio eius molestias odit quis sapiente voluptate! Debitis doloribus eos et ipsa modi molestiae mollitia nulla porro, repellat sunt totam, voluptas. Alias animi consequatur corporis dicta doloremque dolorum error explicabo, in nemo, nobis quibusdam quod rem, tenetur vitae voluptatibus. Aliquid asperiores, assumenda aut error excepturi fuga id illum inventore ipsum magni molestias natus, obcaecati odio officiis perspiciatis quaerat quibusdam quidem quis reiciendis reprehenderit repudiandae suscipit temporibus tenetur ullam, voluptatem! Esse ipsam molestias veritatis! Asperiores consectetur corporis deserunt enim, incidunt modi molestias nam nesciunt non odio optio quas quisquam reiciendis sit tempore, vero voluptates? </p>
                    <p class="mb-4 font-light text-justify text-gray-500 lg:mb-4 md:text-lg lg:text-xl dark:text-gray-400">A animi blanditiis culpa dolore hic libero possimus quasi quia quod, repudiandae, soluta totam velit vitae voluptatem voluptates? Accusamus aliquid blanditiis, consectetur corporis cupiditate deleniti deserunt doloribus ea earum eligendi et explicabo hic in incidunt iste itaque labore magnam nemo numquam officia quae quia quidem quisquam reiciendis sit totam veritatis voluptatum? Animi deleniti eius id in laborum necessitatibus nisi officiis. Aliquid blanditiis, debitis, doloribus dolorum, enim esse eum exercitationem fugit illum ipsam maiores maxime molestias quas rem repellendus reprehenderit saepe sit vero voluptatem voluptatibus? Ab aperiam assumenda aut debitis deleniti dicta maiores modi natus, officiis sequi? Architecto dolorum eos facere porro sint tenetur vitae voluptatum? Cupiditate in iure iusto laboriosam natus possimus quam qui. A alias aliquid amet at commodi culpa expedita fugit harum illum ipsum laboriosam maxime necessitatibus non numquam, perferendis possimus praesentium quae quibusdam, quisquam recusandae reiciendis similique soluta tempore unde, vel velit veniam veritatis. A accusantium aspernatur culpa cupiditate fugit id illum inventore labore laudantium maiores nam necessitatibus nostrum, perspiciatis quaerat quod tempora, temporibus vero. Cumque enim est illum laudantium magni nemo nihil vel! Accusantium at sequi voluptatibus.</p>
                    <p  class="mb-4 font-light text-justify text-gray-500 lg:mb-4 md:text-lg lg:text-xl dark:text-gray-400">Ad at autem consectetur libero, mollitia non perferendis porro ullam. Assumenda eius hic ipsa! Alias aliquid atque, aut, autem corporis culpa dicta doloremque eaque et facere facilis id molestiae nam nobis nulla numquam officia pariatur quis ratione reiciendis similique sunt ut vel vitae voluptas. Alias aliquid at, cum dicta dignissimos hic, id laudantium nisi odit officiis possimus quae quaerat quos, tempora tempore? Amet architecto blanditiis corporis cum distinctio et ex exercitationem, expedita fugit harum id incidunt ipsa ipsam iure nisi obcaecati porro provident repellat repellendus reprehenderit tenetur voluptate voluptatibus voluptatum. Et fugit hic ipsam libero molestiae quas repellendus, sint vel voluptates voluptatum. A accusantium, deserunt dignissimos dolorem esse est ex ipsam iste laboriosam laborum necessitatibus, nostrum numquam optio perferendis rem sapiente vero. A aliquam animi aperiam consequatur, eligendi facere, fuga itaque nam natus perspiciatis quibusdam sed, suscipit veritatis! Deleniti incidunt maiores saepe? Aliquam commodi distinctio dolores earum harum impedit iste libero maiores maxime nulla odio odit omnis, provident quae similique tempore voluptatem voluptatum!</p>
                </div>
            </div>
    </section>
</x-guest-layout>
